### ISSUE TITLE
大佬，我前两天发现挂在服务器上之前一直稳定运行的现在不可以了，输入运行以后是这个样子，之前都没有，你知道是怎么回事吗

### ISSUE THREAD

**Issue by geziye** [Inuyashaaaaa/fzuDailyCampus#4]
[root@VM-0-14-centos src]# ./sign.sh
(node:5671) UnhandledPromiseRejectionWarning: Error: Request failed with status code 405
    at createError (/usr/include/campus_daily_txc/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/include/campus_daily_txc/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/include/campus_daily_txc/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:5671) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5671) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Inuyashaaaaa** [comment]
域名和携带参数变了，最新的已经支持了

**Comment by Inuyashaaaaa** [comment]
注意重新放上去的时候，设置一下 shell文件的格式 set ff=unix

**Comment by geziye** [comment]
好的，谢谢大佬

**Comment by geziye** [comment]
现在改为这个了fzu.campusphere.net是嘛
